### ISSUE TITLE
Deactivated tabs appear on their own on the second restart

### ISSUE THREAD

**Issue by Dhyfer1** [thebookisclosed/ViVe#56] opened 2022-08-20 23:05 UTC
Hi.

I am using the latest version of ViveTool on Windows 11 Beta channel (version 22H2 Compilation 22622.575)

The content of the unzipped Vivetool folder is located at C:\Users\UserName\Downloads\ViveTool

I want to disable the file explorer tabs permanently, so that after every reboot or a shutdown/startup of my PC, the file explorer appears without tabs. So I have used ViveTool (added to the system environment variables) in the command console running as Administrator, so to disable the tabs permanently I have used this code:

`vivetool /disable /id:37634385 /store:both` 37634385 is the ID to activate the tabs in the beta channel

After entering those parameters vivetool says "Successfully set feature configuration", so I restart my PC to apply the changes, and when I open the file explorer I can see that it has no more tabs, but after a second restart the tabs automatically reappear.

Is there any missing parameter in the code I mentioned to disable the tabs permanently or what else can I do about it?

Thanks in advance

**Comment by thebookisclosed** [comment] 2022-08-25 17:38
Please query the ID after it gets re-enabled and paste the output here.

**Comment by Dhyfer1** [comment] 2022-08-26 02:55
Ok. This is the report:

1. With tabs enabled in the file explorer, I check the query for the specific ID with the command:
`vivetool /query /id:37634385` and the result is:
```
[37634385]
Priority        : Service (4)
State           : Enabled (2)
Type            : Override (0)
HasSubscriptions: True
```
2. Then I run the command `vivetool /disable /id:37634385 /store:both` to deactivate the tabs and then restart the PC
3. After rebooting, the explorer has no tabs. So I check the query again and it gives as a result:
```
[37634385]
Priority        : Service (4)
State           : Disabled (1)
Type            : Override (0)
HasSubscriptions: True
```
4. Then, I restart my PC for the second time and when I log in I open the file explorer and I see that the tabs reappeared by on their own. Then I check the query again and the result is the same as before disabling the tabs.
```
[37634385]
Priority        : Service (4)
State           : Enabled (2)
Type            : Override (0)
HasSubscriptions: True
```
I don't know what the problem is, I am waiting for your help.

**Comment by h6fYe34KFSiH** [comment] 2022-10-08 04:01
Same here

**Comment by thebookisclosed** [comment] 2022-10-08 16:32
> Same here

What build are you running? What channel are you enrolled in?

**Comment by Dhyfer1** [comment] 2022-10-09 04:05
@thebookisclosed I still have the same problem, is that there is no definitive solution?

**Comment by ivanez82** [comment] 2022-10-11 15:25
The same problem here..

**Comment by thebookisclosed** [comment] 2022-10-12 12:13
@Dhyfer1 Are you still able to consistently reproduce the issue? If so, can you please check if disabling the `\Microsoft\Windows\Flighting\FeatureConfig\ReconcileFeatures` task makes the unwanted revert on second restart stop happening? Even if it does, please don't keep the task disabled -- it's just a way for me to narrow down the problem & serves as a workaround for the time being.

**Comment by Dhyfer1** [comment] 2022-10-12 23:40
> @Dhyfer1 Are you still able to consistently reproduce the issue? If so, can you please check if disabling the `\Microsoft\Windows\Flighting\FeatureConfig\ReconcileFeatures` task makes the unwanted revert on second restart stop happening? Even if it does, please don't keep the task disabled -- it's just a way for me to narrow down the problem & serves as a workaround for the time being.

Hi. When after a reboot the tabs appeared, I ran vivetool again with the command that I mentioned in my first message `vivetool /disable /id:37634385 /store:both`, but before rebooting I opened the task scheduler and did what you said in https://github.com/thebookisclosed/ViVe/issues/6#issuecomment-670479651 so I deactivated ReconcileFeatures and then restarted my PC.

After turning reboot/restarting my PC several times, the tabs haven't reappeared, but I have noticed that if I turn ReconcileFeatures back on, the tabs reappear, so for now I always have ReconcileFeatures disabled.

Your workaround has been helpful, but are there any consequences for having ReconcileFeatures always disabled?

**Comment by thebookisclosed** [comment] 2022-10-16 13:15
@Dhyfer1 Would you mind sending over your `FeatureConfig*.json` files from `C:\ProgramData\Microsoft\Windows\OneSettings`?

**Comment by Dhyfer1** [comment] 2022-10-16 22:12
@thebookisclosed Of course, here is the file:
[FeatureConfig.zip](https://github.com/thebookisclosed/ViVe/files/9795783/FeatureConfig.zip)

I look forward to hearing from you. Thanks in advance

**Comment by thebookisclosed** [comment] 2022-10-18 11:59
When the task is enabled, do the tabs consistently come back within 2 reboots even if you do them in quick succession or is some waiting required? Having a hard time reproducing this, still

**Comment by thebookisclosed** [comment] 2022-10-19 01:26
v0.3.2 is now out with a /fixpriority command which should fix issues like this one, please try it and let me know if any of the unintended behavior persists.

**Comment by ivanez82** [comment] 2022-10-19 14:22
Apparently in my case the problem has been solved with v0.3.2 and the /fixpriority command, I restarted several times and it has not returned

**Comment by ivanez82** [comment] 2022-10-19 15:13
now with the KB5019509 update i dont get activated the explorer tabs and the other new features.... what i have to do?

**Comment by ivanez82** [comment] 2022-10-19 15:53
Well I fix IDs custom configuration with the /reset commnad.. I hope this is the right way..

**Comment by thebookisclosed** [comment] 2022-10-19 17:29
If you've had a Disable override configured before and wanted them to show up now then yes, a Reset is the correct way to remove the old override.

**Comment by Dhyfer1** [comment] 2022-10-20 02:27
> When the task is enabled, do the tabs consistently come back within 2 reboots even if you do them in quick succession or is some waiting required? Having a hard time reproducing this, still

When the task is activated, sometimes after the first reboot (sometimes after two reboots in a row without waiting time) the tabs reappear just by opening the file explorer once, this is how it worked with the previous version of vivetool 0.3.1.

> Only thing that would make sense to me is for this to either stop reverting (temporarily) or your PC is being served new feature batches at an uncommonly fast rate. If you can consistently reproduce the reverts please check the timestamp of FeatureConfig.json and tell me if it's dated after you've performed the `/disable` command.

You still need to know this? the latest version of vivetool was able to fix the problem, I even re-enabled ReconcileFeatures in the task scheduler and the tabs no longer appear.

> One more small thing, there is no need to explicitly specify /store:both because that is the default behavior.

Hmm. Several months ago, when I used the command `vivetool /disable /id:37634385` for the first time without `/store:both`, on the second reboot the tabs reappeared, so I had to add /store:both, to save the configuration permanently and not disappear after a reboot, and I was guided by what it says [here](https://winaero.com/activate-hidden-features-in-windows-10-insider-builds/#:~:text=In%20addition%2C%20ViveTool%200.3.1%20supports%20the%20/store%20argument%20that%20tells%20the%20app%20where%20to%20write%20the%20changes.%20Use%20it%20as%20follows).

Also vivetool says so when I type `vivetool /enable /?` in cmd:
**Writing to the Boot store is necessary for features to persist across reboots. Changes to this store become
effective the next time you reboot. The Runtime store can be used to make instantenous changes, however not
all features support this, meaning a reboot may be required to apply changes. Use both for best results.**

By the way, I still don't understand how to use the new `/fixpriority` command. With the file explorer without tabs, a couple of days ago I just opened cmd as administrator (before this I had re-enabled the ReconcileFeatures task) and typed vivetool /fixpriority, then I restarted my PC and the explorer was still without tabs, in fact it is still without tabs. But my question is, in a new Windows installation, how do I use this new command to disable tabs permanently? I mean, do I write it like this `vivetool /disable /id:37634385 /store:both /fixpriority` or `vivetool /disable /id:37634385 /fixpriority` or just use `vivetool /fixpriority` after removing the tabs?

**Comment by novincobra** [comment] 2022-10-20 06:50
> Well I fix IDs custom configuration with the /reset commnad.. I hope this is the right way..

I try /fullreset working perfect, after i have problem with update to new windows update oct 2022 not showing tab of new windows feature

**Comment by Dhyfer1** [comment] 2022-10-20 16:31
> Do not rely on tutorials for teaching you good syntax. Additionally what you've cited is simply an explanation of what the stores are for, within that same help text you can also find this.
The parameters in square brackets don't need to be specified and will use these defaults:
Store : Both

Ok. I got it, so the command will use /store:both even if it is not typed in, did I understand correctly?

> /fixpriority is a top-level command, not an argument to use enabling or disabling features.
It's designed for one time use on devices where you've used v0.3.0 or v0.3.1 in the past, just like the changelog says. These versions are unfortunately capable of creating overrides that won't stick perfectly and potentially pause remote feature delivery to your system, unintentionally. Running it on a new install would simply make it say No configurations in this store need to be moved as there is nothing to fix. v0.3.2 and newer create better ("fixed," in this context) overrides by default.

Wait, let me see if I understand. So, in a new Windows installation, I have to use the previous version of vivetool 0.3.1 with the command `vivetool /disable /id:37634385` to disable the tabs and then use vivetool 0.3.2 with the command `vivetool /fixpriority`?

Because if I use the latest version 0.3.2 to disable the tabs and then run vivetool /fixpriority it doesn't work?

**Comment by thebookisclosed** [comment] 2022-10-20 17:33
> Ok. I got it, so the command will use /store:both even if it is not typed in, did I understand correctly?

Yes.

> Wait, let me see if I understand. So, in a new Windows installation, I have to use the previous version of vivetool 0.3.1 with the command `vivetool /disable /id:37634385` to disable the tabs and then use vivetool 0.3.2 with the command `vivetool /fixpriority`?
> 
> Because if I use the latest version 0.3.2 to disable the tabs and then run vivetool /fixpriority it doesn't work?

No! It would be incredibly inconvenient if I released a version that requires you to use another version to achieve what you want. Like I said, **v0.3.2 and newer create better ("fixed," in this context) overrides by default.**
Toggling a feature in v0.3.0/1 and then running `/fixpriority` in v0.3.2 achieves the same end result as simply doing the toggle in v0.3.2 on a device where ViVeTool hasn't been used yet. 
`/fixpriority` is something you should turn to **ONLY** if the device has configurations created by v0.3.0/1, its purpose is to fix bad existing configurations.

**Comment by Dhyfer1** [comment] 2022-10-20 18:29
Ah, ok. I think I'm getting the idea. So this new /fixpriority command should only be used to fix configurations executed with the previous versions of vivetool (0.3.0 and 0.3.1), so I have no need to use /fixpriority if I am **ONLY going to use the latest version** to disable tabs in a clean Windows installation.

So, if I understand correctly, if I only plan to use the latest version 0.3.2 to disable the tabs, I just have to run the command vivetool /disable /id:37634385 and that's it (I won't have to disable the ReconcileFeatures task and I won't have to use /fixpriority).

Did I get it right this time?

**Comment by thebookisclosed** [comment] 2022-10-20 18:37
Yes, that is correct. 😊 I have updated the wording about `/fixpriority` in v0.3.2's changelog to hopefully reduce any future confusion.

**Comment by Dhyfer1** [comment] 2022-10-20 18:43
Ok. Thank you for your patience. I am currently reinstalling Windows, so when I use the latest version of vivetool I will let you know (hours later) if the disabled tabs no longer reappear after more than two system reboots.

**Comment by Dhyfer1** [comment] 2022-10-21 13:52
Hi. The latest version works very well! After reinstalling Windows, and after using the latest version of vivetool with the command `vivetool /disable /id:37634385` the tabs have disappeared forever, even after more than two reboots (up to 7 reboots in a row I have done) the tabs haven't appeared anymore. I didn't need to disable the ReconcileFeatures task and didn't use /fixpriority. So this issue can be closed now.

Thank you! 😊

**Comment by thebookisclosed** [comment] 2022-10-21 15:15
Thank you for the update, closing the issue then 😊

**Closed by thebookisclosed** 2022-10-21 15:15 UTC
Labels: bug, help wanted
